import "@mantine/core/styles.css";
import { ColorSchemeScript, Container, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  // fallback: ["Inter", "sans-serif"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={clsx("min-h-screen h-full flex flex-col w-full antialiased", inter.variable)}>
        <MantineProvider>
        <Nav />
        <div className="p-3 bg-[#eee] min-h-full">
          <Container className="h-full">
            {children}
          </Container>
        </div>
        </MantineProvider>
      </body>
    </html>
  );
}
